language: cpp

# Compile both GCC and Clang
compiler:
##- clang
- gcc

# Install prerequisite packages
#install:
#todo

#env:


# Create makefile
before_script:
- ./Intermediate/CMake/Linux/bin/cmake -G "Unix Makefiles" ./Source

# Compile makefile
script: make
