language: cpp

# Compile both GCC and Clang
compiler:
##- clang
- gcc

# Install prerequisite packages
install:
#todo

env:


# Create makefile
before_script:
- vanguardCmakeExecutable= ./Intermediate/CMake/Linux/bin/cmake
- vanguardSourceRoot= ./Source
- makefileDirectory= ./Intermediate/MakeFile/Makefile
- mkdir -p "$makefileDirectory"
- cd "$makefileDirectory"
- "$vanguardCmakeExecutable" -G "Unix Makefiles" "$vanguardSourceRoot"

# Compile makefile
script: make Intermediate/MakeFile/Makefile
