language: cpp

# Compile both GCC and Clang
compiler:
##- clang
- gcc

addons:
  apt:
    packages:
    - mono-complete
    - g++

# # Install prerequisite packages
# install:
# #Mono
# - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
# - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
# - apt-get update

#env:


# Create makefile
before_script:
- ./Intermediate/CMake/Linux/bin/cmake -G "Unix Makefiles" ./Source

# Compile makefile
script: make
