language: cpp
sudo: true

# Only GCC for coverity.
compiler:
- gcc

# No email notifications
notifications:
  email: false
  
  # Upgrade to g++ 4.8 (needed for c++11 features)
before_install:
- sudo add-apt-repository "ppa:ubuntu-toolchain-r/test" -y
- sudo apt-get update -qq
- sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install --force-yes -qq g++-4.8 ; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# Set for coverity scan.
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sBLzHVSrEqX6RLBVBT2uA/CHYT0HPIaRX/ELMmYns6Htl0EQTQJqFITOs5Nhl15kw5TFBOZuwS6R4ztpQnIBq9na7z/HcAxh1d1r9rT4mCO5KovtHYX7708otckvM/Xz+YfjRTOW6xm1pPBISjqs9rWIZJMVmy2A0b3O7hEmdwDVxKwVJXw2pZiE/rYBJctL3mGOPMru/lnV+omYqGBsPl6xQ5WwNhm+rVStWZRB+IEgEoJx5A8UUW0r33MjKxiRXIdSrDcHMwQozvTOovuo2Q6o4As1/oCBOhAHoS/1ldanm40vn32zmWbKUlK4eEewoLcZVknFVRW6MjN3Lyb7NG3Hw/buvdHxhsCiqBWHEn0AjIKcbWJY5Fmgx3UuXlv2TIzLizOfsQtYGvsu/o28jiUtQAKT3G+v9sR/Gxlv6rzeJt6rKDVyVxd66Raz+BvwAstrjF0KJgtJnkFfFEFRFESjpKRsVcC/SgRUXJZY/+WhH3GlWgCNF5vVlz0+eLcycjPRWjFu/s1f8aea05Lh75VZr5KhDBjCAUHF49kBW5+S+UlxyNTHn8F26FUM+VBRORTNClDZ9sA5CSVVDqAEA8/Cm2s/xw92k5lJUbCXC70RjIqnxjhkUI0HZbJJL9gbHlqawzI9JYvum+FIPWOaPZn4+IIFyqG05vNm/nwHz3E="

# Install mono
addons:
  coverity_scan:
    project:
      name: "MartinPalko/VanguardEngine"
      description: "Build submitted via Travis CI"
    notification_email: jeeprubi@hotmail.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan

# Create makefile
before_script:
- mkdir Intermediate
- cd Intermediate
- cmake -G "Unix Makefiles" ../

# Compile makefile
script:
- if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then (cd ${TRAVIS_BUILD_DIR}/Intermediate && make); fi
