language: cpp

# Compile both GCC and Clang
compiler:
##- clang
- gcc

addons:
  apt:
    packages:
    - mono-complete
    - g++-4.8

# Create makefile
before_script:
- ./Intermediate/CMake/Linux/bin/cmake -G "Unix Makefiles" ./Source

# Compile makefile
script: make
