#pragma once
#include "Platforms/Platform.h"

#include "DynamicLibrary.h"
#include "Mutex.h"
#include "FilePath.h"
#include "IntegerDefs.h"
#include "Quaternion.h"
#include "Rect.h"
#include "VanguardString.h"
#include "StringID.h"
#include "Thread.h"
#include "VanguardTime.h"
#include "Vector2.h"
#include "Vector3.h"